export const LANGUAGES = ['English', 'Spanish', 'Hmong', 'Somali', 'Other']

export const SKILL_CATEGORIES = [
  { value: 'Practical', label: 'Practical / Hands-On' },
  { value: 'Knowledge', label: 'Professional / Knowledge' },
  { value: 'Care', label: 'Care and Community' },
  { value: 'Emergency', label: 'Emergency / Resilience' },
  { value: 'Social', label: 'Social and Cultural' },
]

export const SKILL_OPTIONS: Record<string, string[]> = {
  Practical: [
    'Basic home repairs',
    'Electrical or plumbing knowledge',
    'Car repair',
    'Bike repair',
    'Gardening',
    'Landscaping',
    'Carpentry',
    'Sewing or mending',
    'Tool sharing (ladder, power tools, pressure washer)',
  ],
  Knowledge: [
    'Legal advice (informal guidance)',
    'Financial planning',
    'Grant writing',
    'Graphic design',
    'Social media',
    'IT / tech troubleshooting',
    'Resume help',
    'Translation / bilingual support',
  ],
  Care: [
    'Childcare swaps',
    'Pet sitting',
    'Elder check-ins',
    'Meal trains',
    'First aid / CPR certified',
    'Conflict mediation',
  ],
  Emergency: [
    'Medical training',
    'Generator access',
    'Chainsaw for storm cleanup',
    'Truck for hauling',
    'Ham radio',
    'Solar setup knowledge',
  ],
  Social: [
    'Event planning',
    'Cooking / catering',
    'Music / DJ',
    'Photography',
    'Teaching workshops',
    'Fitness classes',
    'Art instruction',
  ],
}

export const FROGTOWN_STREETS = [
  'Arch St',
  'Arundel St',
  'Aurora Ave',
  'Avon St',
  'Blair Ave',
  'Cedar St',
  'Central Ave W',
  'Charles Ave',
  'Chatsworth St N',
  'Dale St N',
  'Edmund Ave',
  'Elfelt St',
  'Empire Dr',
  'Englewood Ave',
  'Farrington St',
  'Fuller Ave',
  'Galtier St',
  'Grotto St N',
  'Jackson St',
  'Ken St',
  'Lafayette Rd',
  'Lafond Ave',
  'Larch St',
  'Marion St',
  'Milford St',
  'N Fisk St',
  'N Milton St',
  'N Pine St',
  'Olive St',
  'Oxford St',
  'Pierce Butler Rte',
  'Rice St',
  'Robert St',
  'Sherburne Ave',
  'St Albans St',
  'Thomas Ave',
  'University Ave W',
  'Van Buren Ave',
  'Victoria St',
  'Virginia St',
  'W Sycamore St',
  'Western Ave N',
  'Winter St',
  '12th St',
]
